version: "2"
linters:
  enable:
    - asasalint
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - gocritic
    - godox
    - goprintffuncname
    - govet
    - ineffassign
    - intrange
    - makezero
    - mirror
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - predeclared
    - reassign
    - revive
    - staticcheck
    - testableexamples
    - testifylint
    - tparallel
    - unconvert
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wrapcheck
  exclusions:
    presets:
      - comments
formatters:
  enable:
    - gofumpt
    - goimports
