linters:
  enable:
    - errcheck
    - errorlint
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - stylecheck
    - unused
    - whitespace
