version: "2"
linters:
  enable:
    - govet
    - errcheck
    - errorlint
    - misspell
    - revive
    - staticcheck
    - whitespace
    - wrapcheck
    - ineffassign
    - unused
    - unconvert
    - bodyclose
    - copyloopvar
    - nilerr
    - nilnil
    - wastedassign
    - maintidx
    - nakedret
    - predeclared
  exclusions:
    presets:
      - comments
formatters:
  enable:
    - gofmt
