version: "2"
linters:
  enable:
    - errcheck
    - errorlint
    - govet
    - misspell
    - revive
    - staticcheck
    - whitespace
    - wrapcheck
  exclusions:
    presets:
      - comments
formatters:
  enable:
    - gofmt
